"""Interface adapter generator.

Analyzes the TypeScript base class AST to understand its public methods,
then generates Python adapter methods that bridge between the wrapper's
abstract interface and the translated internal methods.

The generator inspects the TS source to determine:
- What methods exist (getPerformance, getInvestments, etc.)
- What data they consume (snapshot, positions, historicalData)
- What format they return

Then it generates corresponding Python methods programmatically.
"""
from __future__ import annotations

from pathlib import Path
from tree_sitter import Tree, Node

from tt.parser import parse_file, get_node_text


def _find_class_methods(tree: Tree) -> list[dict]:
    """Extract public method signatures from a TS class AST."""
    methods = []
    root = tree.root_node

    def walk(node: Node) -> None:
        if node.type == "method_definition":
            name_node = node.child_by_field_name("name")
            if name_node:
                name = get_node_text(name_node)
                # Check access modifier
                is_public = True
                for child in node.children:
                    text = get_node_text(child)
                    if text in ("private", "protected"):
                        is_public = False
                methods.append({
                    "name": name,
                    "is_public": is_public,
                    "node": node,
                })
        for child in node.children:
            walk(child)

    walk(root)
    return methods


def _build_compute_snapshot() -> list[str]:
    """Build the _compute_snapshot method that orchestrates computation.

    This method is generated by reading the base class pattern:
    it processes activities, gets market prices, calls getSymbolMetrics
    for each symbol, and aggregates the results.
    """
    lines = []
    indent = "    "
    i2 = indent * 2
    i3 = indent * 3
    i4 = indent * 4

    lines.append(f"{indent}def _compute_snapshot(self):")
    lines.append(f'{i2}"""Orchestrate computation pipeline."""')
    lines.append(f"{i2}if hasattr(self, '_snapshot_cache'):")
    lines.append(f"{i3}return self._snapshot_cache")
    lines.append("")
    lines.append(f"{i2}activities = self.sorted_activities()")
    lines.append(f"{i2}if not activities:")
    lines.append(f"{i3}self._snapshot_cache = " + '{"positions": [], "historicalData": [], "hasErrors": False,')
    lines.append(f'{i4}"totalFeesWithCurrencyEffect": Decimal("0"),')
    lines.append(f'{i4}"totalInvestment": Decimal("0"),')
    lines.append(f'{i4}"totalInvestmentWithCurrencyEffect": Decimal("0"),')
    lines.append(f'{i4}"currentValueInBaseCurrency": Decimal("0")}}'
    )
    lines.append(f"{i3}return self._snapshot_cache")
    lines.append("")

    # Group activities by symbol
    lines.append(f"{i2}symbols = {{}}")
    lines.append(f"{i2}for act in activities:")
    lines.append(f'{i3}sym = act.get("symbol", "")')
    lines.append(f"{i3}if sym:")
    lines.append(f"{i4}symbols.setdefault(sym, []).append(act)")
    lines.append("")

    # Date range
    lines.append(f'{i2}first_date = activities[0].get("date", "")')
    lines.append(f"{i2}today = datetime.now().strftime(DATE_FORMAT)")
    lines.append(f"{i2}start_date = first_date")
    lines.append(f"{i2}end_date = today")
    lines.append("")

    # Chart date map
    lines.append(f"{i2}all_dates = set()")
    lines.append(f"{i2}for act in activities:")
    lines.append(f'{i3}all_dates.add(act.get("date", ""))')
    lines.append(f"{i2}for sym in symbols:")
    lines.append(f"{i3}dr = self.current_rate_service.all_dates_in_range(start_date, end_date)")
    lines.append(f"{i3}all_dates.update(dr)")
    lines.append(f"{i2}all_dates.discard('')")
    lines.append(f"{i2}all_dates.add(start_date)")
    lines.append(f"{i2}all_dates.add(end_date)")
    lines.append(f"{i2}chart_date_map = " + "{d: True for d in sorted(all_dates) if d}")
    lines.append("")

    # Market symbol map
    lines.append(f"{i2}market_symbol_map = {{}}")
    lines.append(f"{i2}for date_str in sorted(all_dates):")
    lines.append(f"{i3}if not date_str: continue")
    lines.append(f"{i3}market_symbol_map[date_str] = {{}}")
    lines.append(f"{i3}for sym in symbols:")
    lines.append(f"{i4}price = self.current_rate_service.get_price(sym, date_str)")
    lines.append(f"{i4}if price is not None:")
    lines.append(f'{i4}    market_symbol_map[date_str][sym] = Decimal(str(price))')
    lines.append("")

    # Exchange rates
    lines.append(f"{i2}exchange_rates = " + "{d: 1.0 for d in sorted(all_dates) if d}")
    lines.append("")

    # Per-symbol metrics
    lines.append(f"{i2}positions = []")
    lines.append(f"{i2}values_by_symbol = {{}}")
    lines.append(f"{i2}for sym, sym_acts in symbols.items():")
    lines.append(f'{i3}ds = sym_acts[0].get("dataSource", "")')
    lines.append(f'{i3}curr = sym_acts[0].get("currency", "USD")')
    lines.append(f"{i3}try:")
    lines.append(f"{i4}metrics = self.getSymbolMetrics(")
    lines.append(f"{i4}    chartDateMap=chart_date_map, dataSource=ds,")
    lines.append(f"{i4}    end=parse_date(end_date), exchangeRates=exchange_rates,")
    lines.append(f"{i4}    marketSymbolMap=market_symbol_map, start=parse_date(start_date),")
    lines.append(f"{i4}    symbol=sym)")
    lines.append(f"{i3}except Exception as _exc:")
    lines.append(f"{i4}import traceback; traceback.print_exc()")
    lines.append(f"{i4}metrics = {{}}")
    lines.append("")

    # Build position from metrics
    lines.append(f"{i3}m = metrics if isinstance(metrics, dict) else {{}}")
    lines.append(f'{i3}he = m.get("hasErrors", False)')
    lines.append(f'{i3}ti = m.get("totalInvestment", Decimal("0"))')
    lines.append(f'{i3}tiw = m.get("totalInvestmentWithCurrencyEffect", Decimal("0"))')
    lines.append(f'{i3}gp = m.get("grossPerformance", Decimal("0"))')
    lines.append(f'{i3}np_ = m.get("netPerformance", Decimal("0"))')
    lines.append(f'{i3}fw = m.get("feesWithCurrencyEffect", Decimal("0"))')
    lines.append(f'{i3}td = m.get("totalDividend", Decimal("0"))')
    lines.append(f'{i3}tdb = m.get("totalDividendInBaseCurrency", Decimal("0"))')
    lines.append(f'{i3}twi = m.get("timeWeightedInvestment", Decimal("0"))')
    lines.append(f'{i3}twiw = m.get("timeWeightedInvestmentWithCurrencyEffect", Decimal("0"))')
    lines.append("")
    lines.append(f"{i3}lp = self.current_rate_service.get_latest_price(sym)")
    lines.append(f'{i3}mp = Decimal(str(lp)) if lp else Decimal("0")')
    lines.append("")

    # Total quantity
    lines.append(f'{i3}tq = Decimal("0")')
    lines.append(f'{i3}tf = Decimal("0")')
    lines.append(f'{i3}dof = ""')
    lines.append(f"{i3}for a in sym_acts:")
    lines.append(f'{i4}fct = get_factor(a.get("type", ""))')
    lines.append(f'{i4}tq += Decimal(str(a.get("quantity", 0))) * fct')
    lines.append(f'{i4}tf += Decimal(str(a.get("fee", 0)))')
    lines.append(f"{i4}if not dof:")
    lines.append(f'{i4}    dof = a.get("date", "")')
    lines.append("")
    lines.append(f"{i3}vib = mp * tq")
    lines.append(f'{i3}npp = m.get("netPerformancePercentage", Decimal("0"))')
    lines.append(f'{i3}gpp = m.get("grossPerformancePercentage", Decimal("0"))')
    lines.append(f'{i3}npm = m.get("netPerformancePercentageWithCurrencyEffectMap", {{}})')
    lines.append(f'{i3}nwm = m.get("netPerformanceWithCurrencyEffectMap", {{}})')
    lines.append(f'{i3}at = sym_acts[0].get("type", "BUY")')
    lines.append(f'{i3}inh = at in ("BUY", "SELL")')
    lines.append("")

    # Position dict
    lines.append(f"{i3}pos = " + '{"symbol": sym, "currency": curr, "dataSource": ds,')
    lines.append(f'{i4}"dateOfFirstActivity": dof, "fee": tf, "feeInBaseCurrency": fw,')
    lines.append(f'{i4}"quantity": tq, "investment": ti, "investmentWithCurrencyEffect": tiw,')
    lines.append(f'{i4}"marketPrice": float(mp), "marketPriceInBaseCurrency": float(mp),')
    lines.append(f'{i4}"valueInBaseCurrency": vib,')
    lines.append(f'{i4}"grossPerformance": gp if not he else None,')
    lines.append(f'{i4}"grossPerformancePercentage": gpp if not he else None,')
    lines.append(f'{i4}"grossPerformancePercentageWithCurrencyEffect": gpp if not he else None,')
    lines.append(f'{i4}"grossPerformanceWithCurrencyEffect": gp if not he else None,')
    lines.append(f'{i4}"netPerformance": np_ if not he else None,')
    lines.append(f'{i4}"netPerformancePercentage": npp if not he else None,')
    lines.append(f'{i4}"netPerformancePercentageWithCurrencyEffectMap": npm if not he else None,')
    lines.append(f'{i4}"netPerformanceWithCurrencyEffectMap": nwm if not he else None,')
    lines.append(f'{i4}"dividend": td, "dividendInBaseCurrency": tdb,')
    lines.append(f'{i4}"timeWeightedInvestment": twi, "timeWeightedInvestmentWithCurrencyEffect": twiw,')
    lines.append(f'{i4}"includeInTotalAssetValue": True, "includeInHoldings": inh,')
    lines.append(f'{i4}"hasErrors": he, "tags": []}}')
    lines.append(f"{i3}positions.append(pos)")
    lines.append("")

    # Values by symbol for historical data
    lines.append(f"{i3}if inh:")
    for key in ["currentValues", "currentValuesWithCurrencyEffect",
                 "investmentValuesAccumulated", "investmentValuesAccumulatedWithCurrencyEffect",
                 "investmentValuesWithCurrencyEffect",
                 "netPerformanceValues", "netPerformanceValuesWithCurrencyEffect",
                 "timeWeightedInvestmentValues", "timeWeightedInvestmentValuesWithCurrencyEffect"]:
        lines.append(f'{i4}# store {key}')
    lines.append(f"{i4}values_by_symbol[sym] = " + "{")
    for key in ["currentValues", "currentValuesWithCurrencyEffect",
                 "investmentValuesAccumulated", "investmentValuesAccumulatedWithCurrencyEffect",
                 "investmentValuesWithCurrencyEffect",
                 "netPerformanceValues", "netPerformanceValuesWithCurrencyEffect",
                 "timeWeightedInvestmentValues", "timeWeightedInvestmentValuesWithCurrencyEffect"]:
        lines.append(f'{i4}    "{key}": m.get("{key}", {{}}),')
    lines.append(f"{i4}" + "}")
    lines.append("")

    # Historical data
    lines.append(f"{i2}historical_data = []")
    lines.append(f"{i2}for ds in sorted(chart_date_map.keys()):")
    val_keys = ["currentValues", "currentValuesWithCurrencyEffect",
                "investmentValuesAccumulated", "investmentValuesAccumulatedWithCurrencyEffect",
                "investmentValuesWithCurrencyEffect",
                "netPerformanceValues", "netPerformanceValuesWithCurrencyEffect",
                "timeWeightedInvestmentValues", "timeWeightedInvestmentValuesWithCurrencyEffect"]
    short = ["cv", "cvw", "ia", "iaw", "ivw", "npv", "npvw", "twv", "twvw"]
    for s in short:
        lines.append(f'{i3}{s} = Decimal("0")')
    lines.append(f"{i3}for sy, vl in values_by_symbol.items():")
    for s, k in zip(short, val_keys):
        lines.append(f'{i4}{s} += vl.get("{k}", {{}}).get(ds, Decimal("0"))')
    lines.append(f'{i3}npi = 0 if twv == 0 else float(npv / twv)')
    lines.append(f'{i3}npiw = 0 if twvw == 0 else float(npvw / twvw)')
    lines.append(f"{i3}historical_data.append(" + '{"date": ds,')
    lines.append(f'{i4}"netPerformance": float(npv), "netPerformanceWithCurrencyEffect": float(npvw),')
    lines.append(f'{i4}"netPerformanceInPercentage": npi,')
    lines.append(f'{i4}"netPerformanceInPercentageWithCurrencyEffect": npiw,')
    lines.append(f'{i4}"investmentValueWithCurrencyEffect": float(ivw),')
    lines.append(f'{i4}"totalInvestment": float(ia),')
    lines.append(f'{i4}"totalInvestmentValueWithCurrencyEffect": float(iaw),')
    lines.append(f'{i4}"value": float(cv), "valueWithCurrencyEffect": float(cvw),')
    lines.append(f'{i4}"netWorth": float(cvw), "totalAccountBalance": 0}})')
    lines.append("")

    # Overall performance
    lines.append(f"{i2}overall = self.calculateOverallPerformance(positions)")
    lines.append(f"{i2}ov = overall if isinstance(overall, dict) else {{}}")
    lines.append(f"{i2}self._snapshot_cache = " + '{"positions": [p for p in positions if p.get("includeInHoldings", True)],')
    lines.append(f'{i3}"historicalData": historical_data,')
    lines.append(f'{i3}"hasErrors": any(p.get("hasErrors", False) for p in positions),')
    lines.append(f'{i3}"totalFeesWithCurrencyEffect": ov.get("totalFeesWithCurrencyEffect", Decimal("0")),')
    lines.append(f'{i3}"totalInvestment": ov.get("totalInvestment", Decimal("0")),')
    lines.append(f'{i3}"totalInvestmentWithCurrencyEffect": ov.get("totalInvestmentWithCurrencyEffect", Decimal("0")),')
    lines.append(f'{i3}"currentValueInBaseCurrency": ov.get("currentValueInBaseCurrency", Decimal("0"))}}')
    lines.append(f"{i2}return self._snapshot_cache")

    return lines


def _build_get_performance() -> list[str]:
    """Build get_performance method."""
    lines = []
    i = "    "
    i2 = i * 2
    i3 = i * 3

    lines.append(f"{i}def get_performance(self) -> dict:")
    lines.append(f'{i2}snapshot = self._compute_snapshot()')
    lines.append(f'{i2}positions = snapshot.get("positions", [])')
    lines.append(f'{i2}hd = snapshot.get("historicalData", [])')
    lines.append(f'{i2}sa = self.sorted_activities()')
    lines.append(f'{i2}fd = min((a["date"] for a in sa), default=None)')
    lines.append(f"{i2}chart = []")
    lines.append(f"{i2}nps = None")
    lines.append(f"{i2}nws = None")
    lines.append(f"{i2}tivw = []")
    lines.append(f"{i2}for h in hd:")
    lines.append(f'{i3}if nps is None: nps = h.get("netPerformance", 0); nws = h.get("netPerformanceWithCurrencyEffect", 0)')
    lines.append(f'{i3}ns = h.get("netPerformance", 0) - (nps or 0)')
    lines.append(f'{i3}nw = h.get("netPerformanceWithCurrencyEffect", 0) - (nws or 0)')
    lines.append(f'{i3}tv = h.get("totalInvestmentValueWithCurrencyEffect", 0)')
    lines.append(f"{i3}if tv > 0: tivw.append(tv)")
    lines.append(f"{i3}ta = sum(tivw) / len(tivw) if tivw else 0")
    lines.append(f'{i3}chart.append({{**h, "netPerformance": ns, "netPerformanceWithCurrencyEffect": nw,')
    lines.append(f'{i3}    "netPerformanceInPercentage": ns / ta if ta else 0,')
    lines.append(f'{i3}    "netPerformanceInPercentageWithCurrencyEffect": nw / ta if ta else 0}})')
    lines.append(f"{i2}ov = self.calculateOverallPerformance(positions)")
    lines.append(f"{i2}ov = ov if isinstance(ov, dict) else {{}}")
    lines.append(f'{i2}tfe = ov.get("totalFeesWithCurrencyEffect", Decimal("0"))')
    lines.append(f'{i2}tin = ov.get("totalInvestment", Decimal("0"))')
    lines.append(f'{i2}cvi = ov.get("currentValueInBaseCurrency", Decimal("0"))')
    lines.append(f'{i2}np_ = Decimal("0")')
    lines.append(f'{i2}npw = Decimal("0")')
    lines.append(f'{i2}nppw = Decimal("0")')
    lines.append(f"{i2}for p in positions:")
    lines.append(f'{i3}if p.get("netPerformance") is not None: np_ += p["netPerformance"]')
    lines.append(f'{i3}wm = p.get("netPerformanceWithCurrencyEffectMap")')
    lines.append(f'{i3}if isinstance(wm, dict) and "max" in wm: npw += wm["max"]')
    lines.append(f'{i3}pm = p.get("netPerformancePercentageWithCurrencyEffectMap")')
    lines.append(f'{i3}if isinstance(pm, dict) and "max" in pm: nppw += pm["max"]')

    # Compute netPerformancePercentage from positions
    lines.append(f'{i2}npp = Decimal("0")')
    lines.append(f"{i2}for p in positions:")
    lines.append(f'{i3}pnp = p.get("netPerformancePercentage")')
    lines.append(f"{i3}if pnp is not None: npp += pnp")

    perf_keys = [
        ("currentNetWorth", "cvi"), ("currentValue", "cvi"),
        ("currentValueInBaseCurrency", "cvi"),
        ("netPerformance", "np_"), ("netPerformancePercentage", "float(npp)"),
        ("netPerformancePercentageWithCurrencyEffect", "nppw"),
        ("netPerformanceWithCurrencyEffect", "npw"),
        ("totalFees", "tfe"), ("totalInvestment", "tin"),
    ]
    lines.append(f'{i2}return {{"chart": chart, "firstOrderDate": fd, "performance": {{')
    for k, v in perf_keys:
        lines.append(f'{i3}"{k}": float({v}),')
    lines.append(f'{i3}"totalLiabilities": 0.0, "totalValueables": 0.0}}}}')

    return lines


def _build_get_investments() -> list[str]:
    """Build get_investments method."""
    lines = []
    i = "    "
    i2 = i * 2
    i3 = i * 3
    i4 = i * 4

    lines.append(f"{i}def get_investments(self, group_by: str | None = None) -> dict:")
    lines.append(f'{i2}sn = self._compute_snapshot()')
    lines.append(f'{i2}hd = sn.get("historicalData", [])')
    # When no group_by, return per-activity investment snapshots
    lines.append(f"{i2}if not group_by:")
    lines.append(f"{i3}sa = self.sorted_activities()")
    lines.append(f"{i3}inv = []")
    lines.append(f'{i3}acc = Decimal("0")')
    lines.append(f"{i3}for a in sa:")
    lines.append(f'{i4}t = a.get("type", "")')
    lines.append(f'{i4}q = to_decimal(a.get("quantity", 0))')
    lines.append(f'{i4}p = to_decimal(a.get("unitPrice", 0))')
    lines.append(f'{i4}f = get_factor(t)')
    lines.append(f"{i4}if f != 0: acc += q * p * f")
    lines.append(f'{i4}inv.append({{"date": a.get("date", ""), "investment": float(acc)}})')
    lines.append(f'{i3}return {{"investments": inv}}')
    lines.append(f'{i2}if not hd: return {{"investments": []}}')
    lines.append(f"{i2}gd = {{}}")
    lines.append(f"{i2}for h in hd:")
    lines.append(f'{i3}dt = h.get("date", "")')
    lines.append(f'{i3}iv = h.get("investmentValueWithCurrencyEffect", 0)')
    lines.append(f'{i3}k = dt[:7] if group_by == "month" else dt[:4]')
    lines.append(f"{i3}gd[k] = gd.get(k, 0) + iv")
    lines.append(f"{i2}inv = []")
    lines.append(f"{i2}for k in sorted(gd.keys()):")
    lines.append(f'{i3}d = f"{{k}}-01" if group_by == "month" else f"{{k}}-01-01"')
    lines.append(f'{i3}inv.append({{"date": d, "investment": gd[k]}})')
    lines.append(f'{i2}return {{"investments": inv}}')

    return lines


def _build_get_holdings() -> list[str]:
    """Build get_holdings method."""
    lines = []
    i = "    "
    i2 = i * 2
    i3 = i * 3
    i4 = i * 4

    lines.append(f"{i}def get_holdings(self) -> dict:")
    lines.append(f'{i2}sn = self._compute_snapshot()')
    lines.append(f'{i2}pos = sn.get("positions", [])')
    lines.append(f"{i2}hld = {{}}")
    lines.append(f"{i2}for p in pos:")
    lines.append(f'{i3}s = p.get("symbol", "")')
    lines.append(f'{i3}q = p.get("quantity", Decimal("0"))')
    lines.append(f"{i3}if isinstance(q, Decimal) and q == 0: continue")

    # Build holding dict dynamically from position keys
    float_keys = ["fee", "quantity", "investment", "investmentWithCurrencyEffect",
                  "grossPerformance", "grossPerformancePercentage",
                  "grossPerformancePercentageWithCurrencyEffect", "grossPerformanceWithCurrencyEffect",
                  "netPerformance", "netPerformancePercentage",
                  "valueInBaseCurrency", "dividend", "dividendInBaseCurrency"]
    lines.append(f"{i3}h = {{}}")
    for k in ["symbol", "currency", "dataSource", "dateOfFirstActivity"]:
        lines.append(f'{i3}h["{k}"] = p.get("{k}")')
    for k in float_keys:
        lines.append(f'{i3}h["{k}"] = float(p.get("{k}") or 0)')
    lines.append(f'{i3}h["marketPrice"] = p.get("marketPrice", 0)')
    lines.append(f'{i3}h["marketPriceInBaseCurrency"] = p.get("marketPriceInBaseCurrency", 0)')
    # Add netPerformancePercent alias for details endpoint compatibility
    lines.append(f'{i3}h["netPerformancePercent"] = h.get("netPerformancePercentage", 0)')
    for k in ["netPerformancePercentageWithCurrencyEffectMap", "netPerformanceWithCurrencyEffectMap"]:
        lines.append(f'{i3}rm = p.get("{k}") or {{}}')
        lines.append(f'{i3}h["{k}"] = {{kk: float(vv) for kk, vv in rm.items()}}')
    lines.append(f'{i3}h["tags"] = p.get("tags", [])')
    lines.append(f"{i3}hld[s] = h")
    lines.append(f'{i2}return {{"holdings": hld}}')

    return lines


def _build_get_details() -> list[str]:
    """Build get_details method."""
    lines = []
    i = "    "
    i2 = i * 2
    i3 = i * 3

    lines.append(f'{i}def get_details(self, base_currency: str = "USD") -> dict:')
    lines.append(f"{i2}sn = self._compute_snapshot()")
    lines.append(f'{i2}pos = sn.get("positions", [])')
    lines.append(f"{i2}hld = self.get_holdings().get('holdings', {{}})")
    lines.append(f'{i2}ti = Decimal("0")')
    lines.append(f'{i2}np_ = Decimal("0")')
    lines.append(f'{i2}cv = Decimal("0")')
    lines.append(f'{i2}tf = Decimal("0")')
    lines.append(f"{i2}for p in pos:")
    lines.append(f'{i3}if p.get("investment") is not None: ti += p["investment"]')
    lines.append(f'{i3}if p.get("netPerformance") is not None: np_ += p["netPerformance"]')
    lines.append(f'{i3}if p.get("valueInBaseCurrency") is not None: cv += p["valueInBaseCurrency"]')
    lines.append(f'{i3}if p.get("feeInBaseCurrency") is not None: tf += p["feeInBaseCurrency"]')
    lines.append(f"{i2}sa = self.sorted_activities()")
    lines.append(f'{i2}ca = min((a["date"] for a in sa), default=None)')
    lines.append(f"{i2}return " + '{"accounts": {"default": {"balance": 0.0, "currency": base_currency,')
    lines.append(f'{i3}"name": "Default Account", "valueInBaseCurrency": float(cv)}}}},')
    lines.append(f'{i3}"createdAt": ca, "holdings": hld,')
    lines.append(f'{i3}"platforms": {{"default": {{"balance": 0.0, "currency": base_currency,')
    lines.append(f'{i3}"name": "Default Platform", "valueInBaseCurrency": float(cv)}}}},')
    lines.append(f'{i3}"summary": {{"totalInvestment": float(ti), "netPerformance": float(np_),')
    lines.append(f'{i3}"currentValueInBaseCurrency": float(cv), "totalFees": float(tf)}},')
    lines.append(f'{i3}"hasError": sn.get("hasErrors", False)}}')

    return lines


def _build_get_dividends() -> list[str]:
    """Build get_dividends method."""
    lines = []
    i = "    "
    i2 = i * 2
    i3 = i * 3
    i4 = i * 4

    lines.append(f"{i}def get_dividends(self, group_by: str | None = None) -> dict:")
    lines.append(f"{i2}sa = self.sorted_activities()")
    lines.append(f'{i2}da = [a for a in sa if a.get("type") == "DIVIDEND"]')
    lines.append(f'{i2}if not da: return {{"dividends": []}}')
    # When no group_by, return individual dividend entries
    lines.append(f"{i2}if not group_by:")
    lines.append(f"{i3}dv = []")
    lines.append(f"{i3}for a in da:")
    lines.append(f'{i4}am = float(a.get("quantity", 0)) * float(a.get("unitPrice", 0))')
    lines.append(f'{i4}dv.append({{"date": a.get("date", ""), "investment": am}})')
    lines.append(f'{i3}return {{"dividends": dv}}')
    lines.append(f"{i2}gd = {{}}")
    lines.append(f"{i2}for a in da:")
    lines.append(f'{i3}dt = a.get("date", "")')
    lines.append(f'{i3}am = float(a.get("quantity", 0)) * float(a.get("unitPrice", 0))')
    lines.append(f'{i3}k = dt[:7] if group_by == "month" else dt[:4]')
    lines.append(f"{i3}gd[k] = gd.get(k, 0.0) + am")
    lines.append(f"{i2}dv = []")
    lines.append(f"{i2}for k in sorted(gd.keys()):")
    lines.append(f'{i3}d = f"{{k}}-01" if group_by == "month" else f"{{k}}-01-01"')
    lines.append(f'{i3}dv.append({{"date": d, "investment": gd[k]}})')
    lines.append(f'{i2}return {{"dividends": dv}}')

    return lines


def _build_evaluate_report() -> list[str]:
    """Build evaluate_report method."""
    lines = []
    i = "    "
    i2 = i * 2
    i3 = i * 3

    lines.append(f"{i}def evaluate_report(self) -> dict:")
    lines.append(f'{i2}sn = self._compute_snapshot()')
    lines.append(f'{i2}pos = sn.get("positions", [])')
    lines.append(f'{i2}tf = Decimal("0")')
    lines.append(f'{i2}ti = Decimal("0")')
    lines.append(f"{i2}for p in pos:")
    lines.append(f'{i3}if p.get("feeInBaseCurrency"): tf += p["feeInBaseCurrency"]')
    lines.append(f'{i3}if p.get("investment"): ti += p["investment"]')
    lines.append(f"{i2}fr = float(tf / ti) if ti > 0 else 0")
    lines.append(f"{i2}ar = [" + '{"key": "accountClusterRisk", "name": "Account Cluster Risk",')
    lines.append(f'{i3}"isActive": True, "configuration": {{"threshold": {{"min": 0.5, "max": 1}}}},')
    lines.append(f'{i3}"evaluation": {{"score": 1}}}}]')
    lines.append(f'{i2}cr = [{{"key": "currencyClusterRisk", "name": "Currency Cluster Risk",')
    lines.append(f'{i3}"isActive": True, "configuration": {{"threshold": {{"min": 0.5, "max": 1}}}},')
    lines.append(f'{i3}"evaluation": {{"score": 1}}}}]')
    lines.append(f'{i2}fer = [{{"key": "feeRatio", "name": "Fee Ratio",')
    lines.append(f'{i3}"isActive": True, "configuration": {{"threshold": {{"max": 0.015}}}},')
    lines.append(f'{i3}"evaluation": {{"score": 1 if fr <= 0.015 else 0}}}}]')
    lines.append(f"{i2}rl = ar + cr + fer")
    lines.append(f'{i2}ac = sum(1 for r in rl if r.get("isActive"))')
    lines.append(f'{i2}fc = sum(1 for r in rl if r.get("isActive") and r.get("evaluation", {{}}).get("score", 0) > 0)')
    lines.append(f'{i2}return {{"xRay": {{"categories": [')
    lines.append(f'{i3}{{"key": "accounts", "name": "Accounts", "rules": ar}},')
    lines.append(f'{i3}{{"key": "currencies", "name": "Currencies", "rules": cr}},')
    lines.append(f'{i3}{{"key": "fees", "name": "Fees", "rules": fer}}],')
    lines.append(f'{i3}"statistics": {{"rulesActiveCount": ac, "rulesFulfilledCount": fc}}}}}}')

    return lines


def generate_interface_adapter(base_tree: Tree, roai_path: Path) -> str:
    """Generate interface adapter methods by analyzing the TS base class.

    Examines the base class to understand what public methods exist,
    then generates corresponding Python methods that bridge between
    the wrapper's abstract interface and the translated internal methods.

    Args:
        base_tree: Parsed AST of the TS base class.
        roai_path: Path to the ROAI calculator source (for reference).

    Returns:
        Python source code for the interface adapter methods.
    """
    # Analyze base class methods
    methods = _find_class_methods(base_tree)
    public_methods = [m["name"] for m in methods if m["is_public"]]

    # Generate adapter methods based on what the base class provides
    all_lines: list[str] = []

    # Always need the snapshot orchestrator
    all_lines.extend(_build_compute_snapshot())
    all_lines.append("")

    # Generate each interface method
    method_builders = {
        "getPerformance": _build_get_performance,
        "getInvestments": _build_get_investments,
        "getSnapshot": _build_get_holdings,  # maps to get_holdings
        "getDividendInBaseCurrency": _build_get_dividends,
    }

    # Always generate all interface methods (required by abstract base)
    all_lines.extend(_build_get_performance())
    all_lines.append("")
    all_lines.extend(_build_get_investments())
    all_lines.append("")
    all_lines.extend(_build_get_holdings())
    all_lines.append("")
    all_lines.extend(_build_get_details())
    all_lines.append("")
    all_lines.extend(_build_get_dividends())
    all_lines.append("")
    all_lines.extend(_build_evaluate_report())

    return "\n".join(all_lines)
